
export {default as homeru} from "./home-ru.png"
export {default as homebw} from "./home-bw.png"
export {default as nextsec} from "./next-sec.png"
export {default as nextsec2} from "./next-sec-2.png"
export {default as pro1} from "./pro1.png"
export {default as pro2} from "./pro2.png"
export {default as pro3} from "./pro3.png"
export {default as pro4} from "./pro4.png"
export {default as pro5} from "./pro5.png"
export {default as pro6} from "./pro6.png"